version: '3.9'

services:
  website:
    image: ghcr.io/afidzulinn/portofolio:main
    container_name: website-mamang
    ports:
      - '8084:80'
    restart: unless-stopped


networks:
  default:
    name: website_network