version: '3.9'

services:
  website:
    image: ghcr.io/afidzulinn/portofolio:main
    container_name: website-mamang
    ports:
      - '8084:80'
    restart: unless-stopped


networks:
  default:
    name: website_network


# version: '3.8'

# services:
#     image: laravel-app
#     container_name: laravel-app
#     restart: unless-stopped
#     environment:
#       - APP_ENV=${APP_ENV}
#       - APP_KEY=${APP_KEY}
#       - APP_DEBUG=${APP_DEBUG}
#       - APP_URL=${APP_URL}
#       - DB_CONNECTION=mysql
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=${DB_DATABASE}
#       - DB_USERNAME=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#     volumes:
#       - ./:/var/www/html
#     ports:
#       - "8080:80" ===> menyesuaikan
#     depends_on:
#       - db
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   dbdata:
